# Generated by Django 5.0.6 on 2024-07-08 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descuento', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('creado', models.DateTimeField(auto_now=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-creado'],
            },
        ),
    ]
