# Generated by Django 5.0.6 on 2024-06-30 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('anfitrion', models.CharField(max_length=80)),
                ('capacidad', models.IntegerField()),
                ('camas', models.IntegerField()),
                ('costo_noche', models.FloatField()),
                ('servicios', models.CharField(max_length=500)),
                ('ubicacion', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descuento', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=20)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenCabana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.CharField(max_length=200)),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.cabana')),
            ],
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.cabana')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registros.promocion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=300)),
                ('numero_estrellas', models.IntegerField()),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.cabana')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.usuario')),
            ],
        ),
    ]
