# Generated by Django 5.0.6 on 2024-07-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=20)),
                ('imagen', models.ImageField(null=True, upload_to='imgUsers', verbose_name='Imagen')),
                ('admin', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-creado'],
            },
        ),
    ]
