# Generated by Django 5.0.6 on 2024-07-08 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_cabanas', '0001_initial'),
        ('admin_users', '0001_initial'),
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('creado', models.DateTimeField(auto_now=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True, null=True)),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_cabanas.cabana')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promociones.promocion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_users.usuario')),
            ],
            options={
                'verbose_name': 'Renta',
                'verbose_name_plural': 'Rentas',
                'ordering': ['-creado'],
            },
        ),
    ]
